### ISSUE TITLE
CONTRIBUTING.md - Aggiornamento URL

### ISSUE THREAD

**Issue by phox081** [vuejs-translations/docs-it#156]
Ciao @ilpaolino, ti taggo qui per le modifiche da apportare 
- al file CONTRIBUTING.md nella root 
- e alla discussione: https://github.com/vuejs-translations/docs-it/discussions/78

**Comment by ilpaolino** [comment]
@phox081 fatto, aperta PR:
https://github.com/vuejs-translations/docs-it/pull/157
