### ISSUE TITLE
partners

### ISSUE THREAD

**Issue by phox081** [vuejs-translations/docs-it#30]
**File da tradurre c'è solo il JSON dei partner che cambia periodicamente, direi che non è urgente**

partners
partners/index.md
partners/partnerId.md
partners/all.md_

**Comment by AlessioChen** [comment]
@phox081 qui direi che va tradotto partners.json ?

**Comment by phox081** [comment]
> @phox081 qui direi che va tradotto partners.json ?

@AlessioChen  se non c'è testo nei file segnati, per favore modifica la descrizione della issue con i file corretti, se c'è un json procedi con quello.
