### ISSUE TITLE
partners/components

### ISSUE THREAD

**Issue by phox081** [vuejs-translations/docs-it#31]
File da tradurre

partners/components
  - [x] PartnerAll.vue
  - [x] PartnerCard.vue - nulla da tradurre
  - [x] PartnerHero.vue
  - [x] PartnerJoin.vue
  - [x] PartnerLanding.vue
  - [x] PartnerList.vue
  - [x] PartnerLocation.vue - nulla da tradurre
  - [x] PartnerPage.vue

**Comment by DomeT99** [comment]
Ciao, se volete potete assegnare a me la sezione "partner", sarei felice di darvi una mano :)
