### ISSUE TITLE
translations/index.md

### ISSUE THREAD

**Issue by phox081** [vuejs-translations/docs-it#4]
File tradotto,
al rilascio finale va aggiunto link Ita dopo il merge con origin per recuperare le ultime modifiche

**Comment by AlessioChen** [comment]
@phox081 lo vedo già tradotto.

**Comment by phox081** [comment]
Merge fatto 11/10/2023, ore 20:12
siamo on line
PR su repo principale: https://github.com/vuejs/docs/pull/2533
